config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  # create all the routes for different actions for our application
  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  # root directory
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]

    def index
        @docs = Doc.where(user_id: current_user).order("created_at DESC")
    end

    def show
    end

    def new
        @doc = current_user.docs.build
    end

    def create
        @doc = current_user.docs.build(doc_params)

        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end
    end

    def destroy
        @doc.destroy
        redirect_to docs_path
    end

    private

        def find_doc
            @doc = Doc.find(params[:id])
        end
        
        def doc_params
            params.require(:doc).permit(:title, :content)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit

app/views/docs/edit.html.haml
%h1 Edit Note


= render 'form'

%button= link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
    #docs.clearfix
        - unless @docs.blank?
            - @docs.each do |doc|
                %a{ href: (url_for [doc])} 
                    .doc
                        %p.title= doc.title
                        %p.date= time_ago_in_words(doc.created_at)
                        %p.content= truncate(doc.content, length:50)
        - else
            %h2 Create Doc!
            %p Start Creating Documents and Organizing your life!
            %button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h1 New Note

= render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
    #doc_show
        %h1.title= @doc.title
        %p= @doc.content

        .buttons
            = link_to "Edit", edit_doc_path(@doc)
            |
            = link_to "Delete", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}

app/views/layouts/application.html.haml
!!!
%html
%head
  %title NeverNote | Always You!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  

%body
  .navbar.navbar-light.bg-light
    .header_inner
      = link_to image_tag("/assets/Nevernote.png"), root_path
    %nav
      - if user_signed_in?
        %button= link_to "New Note", new_doc_path
        |
        %button= link_to "Sign Out", destroy_user_session_path, method: :delete

      - else 
        %button= link_to "Log In", new_user_session_path
        %span.or or
        %button= link_to "Sign Up", new_user_registration_path
  .nav
    %span.notice= notice
    %span.alert= alert

  = yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
#banner
    .banner_content
        %h1 Nevernote
        %p Never get disorganized again.
        -# %button=link_to "Sign In", new_user_session_path
        -# %span or
        -# %button= link_to "Sign Up", new_user_registration_path
%br/
#callouts
    .callout_inner
        .wrapper
            .callout
                %br/
                %h2 Our Purpose
                %p We all know we need to take control of our lives. 
                %p So here is your chance to get control, let your day be won, not done.
    .images
        = link_to image_tag("../assets/images/set.png"), "https://nevernotekde.herokuapp.com/users/sign_up"
        = link_to image_tag("/assets/do.png"), "https://nevernotekde.herokuapp.com/users/sign_up"
        = link_to image_tag("/assets/befree.png"), "https://nevernotekde.herokuapp.com/users/sign_up"
#footer.footer-distributed  
    .footer-left
        %p.footer-links
            = link_to image_tag("/assets/Nevernote.png"), root_path
            %a= link_to "Home", root_path
            |
            %a= link_to "Sign Up", new_user_registration_path
            |
            %a(href="/")= link_to "Sign In", new_user_session_path
        %p.footer-company-name
            Nevernote &copy; 2018
    .footer-center
        %div
        %p Dallas, Tx, 75211
        %div
        %p 469-514-0883
        %div
        %a= link_to "https://www.linkedin.com/in/kiethechols/"
    .footer-right 

        %p.footer-company-about
            %span About the Company
            %p.green Get organized, with Nevernote.